version: '3.8'
services:
  database:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - "./data:/var/lib/postgresql"
    ports:
      - "5433:5432"
  client_db:
    container_name: pg_initializer
    build: ./psql_client/
    volumes:
      - "./data:/var/lib/postgresql/"
    command: ["/bin/sh", "/var/lib/postgresql/commands/comandos_ejecutar.sh"]
    depends_on:
      - database
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"